# Generated by Django 2.2.4 on 2021-04-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabowrite_app', '0002_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='board_image',
            field=models.CharField(max_length=100),
        ),
    ]
