# Generated by Django 2.2.4 on 2021-04-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabowrite_app', '0004_post_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=models.CharField(max_length=1500),
        ),
    ]
